### ISSUE TITLE
Trying to load audio files from scard

### ISSUE THREAD

**Issue by b2renger** [MeULEDs/apwidgets#1]
Hello 

I'm trying to use apwidgets with select-file (https://github.com/pif/android-select-file), my goal as stated is to load a file from my sdcard to be played by the media player.

In the source I see that setMediaFile checks in the assets folder : https://github.com/MeULEDs/apwidgets/blob/master/src/apwidgets/APMediaPlayer.java#L72

is there a simple way to override that ?

**Comment by MeULEDs** [comment]
Hello! Unfortunately we didn't write the APWidgets library and can't answer your question. We just forked it from:

https://code.google.com/p/apwidgets/ 

I'm not sure if the original author is still supporting the code but if you go to the link above his contact information should be there. Hope you're able to find an answer!
